# Change these first
owner: facundomdu # Your GitHub organization or username, where this repository lives
repo: mdu-github-glb-monitor-01 # The name of this repository

sites:
  - name: Misiones
    url: https://misiones.gob.ar
    icon: https://misiones.gob.ar/favicon.ico
  - name: Salud
    url: https://salud.misiones.gob.ar
  - name: RPI
    url: https://rpi.misiones.gob.ar
  - name: Marandu
    url: https://marandu.com.ar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /mdu-github-glb-monitor-01
  favicon: https://misiones.gob.ar/favicon.ico
  logoUrl: https://marandu.com.ar/wp-content/themes/marandu/images/marandu-logo.gif
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor externo MDU
  introTitle: "Monitor externo MDU"
 # introMessage: Esta es una página de estado de muestra que usa datos en tiempo real de nuestros sistemas
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
