# Change these first
owner: facundomdu # Your GitHub organization or username, where this repository lives
repo: mdu-github-glb-monitor-01 # The name of this repository

sites:
#ORDENAR POR ABECEDARIO NOMBRE Y DOMINIO 
# VER OPCION PARA APRUPAR (institucionales, endpoints, apis, etc)

  - name: Misiones
    url: https://misiones.gob.ar
    icon: https://misiones.gob.ar/favicon.ico
  - name: Marandu
    url: https://marandu.com.ar

#INSTITUCIONALES 
  - name: acmcimisionesgobar
    url: https://acmci.misiones.gob.ar/
  - name: agrifam.misiones.gob.ar
    url: https://agrifam.misiones.gob.ar/
  - name: agro.misiones.gob.ar
    url: https://agro.misiones.gob.ar/
  - name: ahora.misiones.gob.ar
    url: https://ahora.misiones.gob.ar/
  - name: biofabrica.misiones.gob.ar
    url: https://biofabrica.misiones.gob.ar/
  - name: cea.misiones.gob.ar
    url: https://cea.misiones.gob.ar/
  - name: ceambiental.misiones.gob.ar
    url: https://ceambiental.misiones.gob.ar/
  - name: www.cocinamisionera.com.ar
    url: https://www.cocinamisionera.com.ar/
  - name: comunicacion.misiones.gob.ar
    url: https://comunicacion.misiones.gob.ar/
  - name: congresojovenesfira-cila.com.ar
    url: https://congresojovenesfira-cila.com.ar/
  - name: defensoriadennya.misiones.gob.ar
    url: https://defensoriadennya.misiones.gob.ar/
  - name: derechoshumanos.misiones.gob.ar
    url: https://derechoshumanos.misiones.gob.ar/
  - name: desarrollosocial.misiones.gob.ar
    url: https://desarrollosocial.misiones.gob.ar/
  - name: ecologia.misiones.gob.ar
    url: https://ecologia.misiones.gob.ar/
  - name: edu.misiones.gob.ar
    url: https://edu.misiones.gob.ar/  
  - name: expomujer.misiones.gob.ar
    url: https://expomujer.misiones.gob.ar/
  - name: fiestadelinmigrante.com.ar
    url: https://fiestadelinmigrante.com.ar/
  - name: fiscaliadeestado.misiones.gob.ar
    url: https://fiscaliadeestado.misiones.gob.ar/
  - name: fondocredito.misiones.gob.ar
    url: https://fondocredito.misiones.gob.ar/
  - name: gobierno.misiones.gob.ar
    url: https://gobierno.misiones.gob.ar/ 
  - name: guacurari.misiones.gob.ar
    url: https://guacurari.misiones.gob.ar
  - name: htc.misiones.gob.ar
    url: https://htc.misiones.gob.ar/
  - name: iaavim.misiones.gob.ar
    url: https://iaavim.misiones.gob.ar/
  - name: ide.marandu.com.ar
    url: https://ide.marandu.com.ar/
  - name: www.misiones.gob.ar
    url: https://www.misiones.gob.ar/
  - name: museocambas.marandu.com.ar
    url: https://museocambas.marandu.com.ar/
  - name: rpi.misiones.gob.ar
    url: https://rpi.misiones.gob.ar
  - name: salud.misiones.gob.ar
    url: https://salud.misiones.gob.ar
  - name: trabajomisionesgob_ar  
    url: https://trabajo.misiones.gob.ar/


#CHEKEO DE SISTEMAS FRONTEND
  - name: sysrpimisionesgob-ar
    url: https://sys.rpi.misiones.gob.ar
  - name: cio911misionesgobar
    url: http://cio911.misiones.gob.ar/

#CHEKEO DE SISTEMAS BACKEND
# eectoral test
  - name: electoralA
    url: https://electoral2021.misiones.gob.ar/
    headers:
      - "Server: electoral-site-a"
      - "Content-Type: text/html"

  - name: electoralB
    url: https://electoral2021.misiones.gob.ar/
    headers:
      - "Server: electoral-site-b"
      - "Content-Type: text/html"


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /mdu-github-glb-monitor-01
  favicon: https://misiones.gob.ar/favicon.ico
  logoUrl: https://marandu.com.ar/wp-content/themes/marandu/images/marandu-logo.gif
  #themeUrl: https://github.com/facundomdu/mdu-github-glb-monitor-01/blob/master/assets/misiones-theme.css
#  themeUrl: https://facundomdu.github.io/mdu-github-glb-monitor-01/global.css
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  links:
    - rel: stylesheet
      href: https://halianelf.github.io/css/upptime.css
  name: Monitor externo MDU
  introTitle: "Monitor externo MDU"
 # introMessage: Esta es una página de estado de muestra que usa datos en tiempo real de nuestros sistemas
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


# logo futher mdu-blanco-tranpa.png
